spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    maximum-pool-size: 150
    minimum-idle: 20
    max-active: 500
    hikari:
      maximum-pool-size: 150
      minimum-idle: 20
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379